# Generated by Django 5.2.13 on 2026-04-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_facilitators_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitator',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='facilitator',
            name='surname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
