# Generated by Django 5.2.13 on 2026-04-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_facilitator_name_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_time', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_fields', models.TextField(blank=True, null=True)),
                ('old_values', models.TextField(blank=True, null=True)),
                ('new_values', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('citizen', models.CharField(blank=True, max_length=255, null=True)),
                ('race_gender', models.CharField(blank=True, max_length=255, null=True)),
                ('work_stations', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Learners',
            },
        ),
    ]
