# Generated by Django 5.2.13 on 2026-04-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_learners_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_time', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_fields', models.TextField(blank=True, null=True)),
                ('old_values', models.TextField(blank=True, null=True)),
                ('new_values', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('days', models.CharField(blank=True, max_length=100, null=True)),
                ('rmaa_members', models.CharField(blank=True, max_length=100, null=True)),
                ('non_members', models.CharField(blank=True, max_length=100, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'FeeStructure',
                'ordering': ['sort_order'],
            },
        ),
    ]
