# Generated by Django 5.2.13 on 2026-06-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_fee_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='RmaaContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'RmaaContacts',
            },
        ),
    ]
