# Generated by Django 5.2.13 on 2026-06-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rmaacontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='abattoirmaster',
            name='market_access_apv_contact_cell',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='abattoirmaster',
            name='market_access_apv_contact_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abattoirmaster',
            name='market_access_apv_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abattoirmaster',
            name='market_access_export_contact_cell',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='abattoirmaster',
            name='market_access_export_contact_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abattoirmaster',
            name='market_access_export_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
