# Generated by Django 5.2.13 on 2026-07-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_abattoirmaster_market_access_apv_contact_cell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='day_fee',
            field=models.BooleanField(default=False),
        ),
    ]
